version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  url-shortener:
    build:
      context: ./url-shortener
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "1110:1110"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  url-resolver:
    build:
      context: ./url-resolver
      dockerfile: Dockerfile
    container_name: url-resolver
    ports:
      - "1111:1111"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
