apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-resolver
  template:
    metadata:
      labels:
        app: url-resolver
    spec:
      containers:
        - name: url-resolver
          image: manas14935/url-resolver:latest
          ports:
            - containerPort: 1111
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: url-resolver
spec:
  selector:
    app: url-resolver
  ports:
    - port: 1111
      targetPort: 1111
      nodePort: 31111
  type: NodePort
