name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_SHORTENER: manas14935/url-shortener
  IMAGE_RESOLVER: manas14935/url-resolver

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build URL Shortener
        working-directory: url-shortener
        run: ./gradlew clean build --no-daemon

      - name: Build URL Resolver
        working-directory: url-resolver
        run: ./gradlew clean build --no-daemon

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push url-shortener image
        run: |
          docker build -t $IMAGE_SHORTENER:latest ./url-shortener
          docker push $IMAGE_SHORTENER:latest

      - name: Build and push url-resolver image
        run: |
          docker build -t $IMAGE_RESOLVER:latest ./url-resolver
          docker push $IMAGE_RESOLVER:latest

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl get pods

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          helm upgrade --install tinyurl ./tinyurl \
            --set url-shortener.image.repository=$IMAGE_SHORTENER \
            --set url-resolver.image.repository=$IMAGE_RESOLVER \
            --set url-shortener.image.tag=latest \
            --set url-resolver.image.tag=latest
